version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: expencies_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - expencies-network
    
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
    - "6379:6379"
    volumes:
    - redis_data:/data
    networks:
    - expencies-network

  app:
    build: .
    container_name: app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - expencies-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/expencies_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

volumes:
  postgres_data:
  redis_data:

networks:
  expencies-network:
    driver: bridge